$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: ml-project-env
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
conda_file: ../environment.yml
description: Custom Azure ML environment using Conda
